In [10]:
import pandas as pd
import constants as const
from custom_encoder import Encoder
from sklearn.utils import shuffle

df = pd.read_pickle('../prepared_data/companies_people_fortified.pkl')
encoder = Encoder(const.ALPHABET)

In [11]:
df

                                                        0  1
0                              донобаев болот орозалыевич  1
1       общество с ограниченной ответственностью "tnc ...  0
2       учреждение "ошская городская инспекция по вете...  0
3                                 тен владимир валерьевич  1
4                              розметов шерали итахунович  1
5                                     осоо "ивента групп"  0
6                               койчиева замира капаровна  1
7                                   у-е с. ш. "айдын-кол"  0
8                             тынянова татьяна николаевна  1
9                                          отунчиев жениш  1
10      общество с ограниченной ответственностью "баргек"  0
11                                      жакышев мамасадык  1
12      общественное объединение попечительский совет ...  0
13                  общественное объединение "friendship"  0
14                                урсус плюс (ursus plus)  0
15                                     осоо "восток-урал"  0
16                      джунусов кубанычбек абдубаитович   1
17                            божоков талыпжан аппазович   1
18                          суюмбаева айнура ахматбековна  1
19                                         мухаммад намаз  1
20                                      осоо "сем и нур"   0
21      товарищество собственников жилых и нежилых пом...  0
22                                      осоо "акцент юг"   0
23                        назарова турганжан абдыбаповна   1
24                                              мин темир  0
25                        мамытшаева гулбурак мамытшаевна  1
26                            байсынов урмат калыбекович   1
27                                                    эрт  0
28       общество с ограниченной ответственностью "белек"  0
29          сельское инвестиционное объединение "жайылма"  0
...                                                   ... ..
189582                                          богалинин  0
189583                     балтабаев назирбек абдылдаевич  1
189584                                 осоо "шинтай груп"  0
189585                        кененбаева зарифа сыдыковна  1
189586                      чернобровкин данил михайлович  1
189587                       федосов сергей александрович  1
189588                    осмоналиев бакытбек абдылдаевич  1
189589                   абдырахманова анаркул карыбаевна  1
189590                   мураталиева сабира насердиновна   1
189591  общество с ограниченной ответственностью "баяс...  0
189592          оо защита прав оздоровительных комплексов  0
189593                     жаныбеков эрланбек жаныбекович  1
189594                                      мануйлов м.г.  1
189595                         нурланов талгат сатбекович  1
189596                        аматов бекмир анварбекович   1
189597                        общественный фонд "билик-1"  0
189598      осоо "seacrest" ("сикрест сиайэс") (иу-индия)  0
189599  общество с ограниченной ответственностью "хюнд...  0
189600                            усонов иса мурзапарович  1
189601  у-е"южное межрегиональное управление профессио...  0
189602                                    кызыл-кыя майы   0
189603  общество с ограниченной ответственностью "absa...  0
189604                         руденко ольга владимировна  1
189605    общество с ограниченной ответственностью "улес"  0
189606                 мамажанов субатылло хабибуллаевич   1
189607  общество с ограниченной ответственностью "алип...  0
189608                       мамыралиев талапташ досуевич  1
189609                                      маткаримов м.  1
189610                                 исмик исмаил месут  1
189611                     салиева атыргул кубанычбековна  1

[189612 rows x 2 columns]

In [12]:
df[0] = encoder.tokenize(df[0])

In [13]:
df

                                                        0  1
0       [4, 15, 14, 15, 2, 1, 5, 22, 27, 2, 15, 12, 15...  1
1       [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
2       [21, 3, 18, 5, 26, 4, 5, 14, 9, 5, 27, 28, 15,...  0
3       [20, 5, 14, 27, 22, 12, 1, 4, 9, 13, 9, 18, 27...  1
4       [18, 15, 26, 13, 5, 20, 15, 22, 27, 19, 5, 18,...  1
5       [15, 19, 15, 15, 27, 28, 9, 22, 5, 14, 20, 1, ...  0
6       [11, 15, 10, 3, 9, 5, 22, 1, 27, 26, 1, 13, 9,...  1
7       [21, 28, 5, 27, 19, 28, 27, 19, 28, 27, 28, 1,...  0
8       [20, 25, 14, 1, 14, 15, 22, 1, 27, 20, 1, 20, ...  1
9       [15, 20, 21, 14, 3, 9, 5, 22, 27, 26, 5, 14, 9...  1
10      [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
11      [26, 1, 11, 25, 19, 5, 22, 27, 13, 1, 13, 1, 1...  1
12      [15, 2, 19, 5, 19, 20, 22, 5, 14, 14, 15, 5, 2...  0
13      [15, 2, 19, 5, 19, 20, 22, 5, 14, 14, 15, 5, 2...  0
14      [21, 18, 19, 21, 19, 27, 16, 12, 21, 19, 27, 2...  0
15      [15, 19, 15, 15, 27, 28, 22, 15, 19, 20, 15, 1...  0
16      [4, 26, 21, 14, 21, 19, 15, 22, 27, 11, 21, 2,...  1
17      [2, 15, 26, 15, 11, 15, 22, 27, 20, 1, 12, 25,...  1
18      [19, 21, 21, 13, 2, 1, 5, 22, 1, 27, 1, 10, 14...  1
19      [13, 21, 8, 1, 13, 13, 1, 4, 27, 14, 1, 13, 1,...  1
20      [15, 19, 15, 15, 27, 28, 19, 5, 13, 27, 9, 27,...  0
21      [20, 15, 22, 1, 18, 9, 19, 5, 19, 20, 22, 15, ...  0
22      [15, 19, 15, 15, 27, 28, 1, 11, 3, 5, 14, 20, ...  0
23      [14, 1, 26, 1, 18, 15, 22, 1, 27, 20, 21, 18, ...  1
24                      [13, 9, 14, 27, 20, 5, 13, 9, 18]  0
25      [13, 1, 13, 25, 20, 19, 1, 5, 22, 1, 27, 7, 21...  1
26      [2, 1, 10, 19, 25, 14, 15, 22, 27, 21, 18, 13,...  1
27                                            [5, 18, 20]  0
28      [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
29      [19, 5, 12, 28, 19, 11, 15, 5, 27, 9, 14, 22, ...  0
...                                                   ... ..
189582                    [2, 15, 7, 1, 12, 9, 14, 9, 14]  0
189583  [2, 1, 12, 20, 1, 2, 1, 5, 22, 27, 14, 1, 26, ...  1
189584  [15, 19, 15, 15, 27, 28, 19, 9, 14, 20, 1, 10,...  0
189585  [11, 5, 14, 5, 14, 2, 1, 5, 22, 1, 27, 26, 1, ...  1
189586  [3, 5, 18, 14, 15, 2, 18, 15, 22, 11, 9, 14, 2...  1
189587  [6, 5, 4, 15, 19, 15, 22, 27, 19, 5, 18, 7, 5,...  1
189588  [15, 19, 13, 15, 14, 1, 12, 9, 5, 22, 27, 2, 1...  1
189589  [1, 2, 4, 25, 18, 1, 8, 13, 1, 14, 15, 22, 1, ...  1
189590  [13, 21, 18, 1, 20, 1, 12, 9, 5, 22, 1, 27, 19...  1
189591  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189592  [15, 15, 27, 26, 1, 19, 9, 20, 1, 27, 16, 18, ...  0
189593  [26, 1, 14, 25, 2, 5, 11, 15, 22, 27, 5, 18, 1...  1
189594  [13, 1, 14, 21, 10, 12, 15, 22, 27, 13, 28, 7,...  1
189595  [14, 21, 18, 12, 1, 14, 15, 22, 27, 20, 1, 12,...  1
189596  [1, 13, 1, 20, 15, 22, 27, 2, 5, 11, 13, 9, 18...  1
189597  [15, 2, 19, 5, 19, 20, 22, 5, 14, 14, 25, 10, ...  0
189598  [15, 19, 15, 15, 27, 28, 19, 5, 1, 3, 18, 5, 1...  0
189599  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189600  [21, 19, 15, 14, 15, 22, 27, 9, 19, 1, 27, 13,...  1
189601  [21, 28, 5, 28, 21, 26, 14, 15, 5, 27, 13, 5, ...  0
189602  [11, 25, 26, 25, 12, 28, 11, 25, 1, 27, 13, 1,...  0
189603  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189604  [18, 21, 4, 5, 14, 11, 15, 27, 15, 12, 28, 7, ...  1
189605  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189606  [13, 1, 13, 1, 26, 1, 14, 15, 22, 27, 19, 21, ...  1
189607  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189608  [13, 1, 13, 25, 18, 1, 12, 9, 5, 22, 27, 20, 1...  1
189609  [13, 1, 20, 11, 1, 18, 9, 13, 15, 22, 27, 13, 28]  1
189610  [9, 19, 13, 9, 11, 27, 9, 19, 13, 1, 9, 12, 27...  1
189611  [19, 1, 12, 9, 5, 22, 1, 27, 1, 20, 25, 18, 7,...  1

[189612 rows x 2 columns]

In [14]:
df = shuffle(df).reset_index(drop=True)

In [15]:
df

                                                        0  1
0                [16, 15, 12, 27, 1, 18, 9, 4, 26, 9, 20]  1
1            [15, 15, 15, 27, 28, 2, 5, 14, 4, 1, 28, 27]  0
2       [19, 21, 12, 1, 10, 13, 1, 14, 28, 20, 15, 15,...  0
3       [20, 15, 11, 13, 15, 11, 19, 11, 9, 10, 27, 19...  0
4       [13, 1, 20, 22, 5, 5, 14, 11, 15, 27, 9, 18, 9...  1
5       [14, 21, 18, 5, 12, 27, 11, 21, 18, 21, 12, 21...  0
6       [13, 5, 11, 20, 5, 16, 27, 2, 15, 18, 21, 28, ...  0
7                          [18, 15, 1, 12, 1, 22, 20, 15]  0
8                  [19, 9, 14, 28, 19, 5, 14, 27, 11, 15]  0
9       [11, 21, 20, 21, 19, 5, 22, 1, 27, 9, 2, 1, 18...  1
10      [2, 12, 1, 7, 15, 20, 22, 15, 18, 9, 20, 5, 12...  0
11      [7, 15, 12, 5, 14, 11, 15, 27, 1, 12, 5, 11, 1...  1
12        [1, 7, 1, 6, 15, 14, 15, 22, 27, 22, 28, 1, 28]  1
13      [15, 18, 13, 15, 14, 15, 22, 27, 15, 13, 21, 1...  1
14      [2, 9, 10, 26, 1, 5, 22, 27, 26, 15, 18, 2, 5,...  1
15      [9, 19, 1, 11, 21, 14, 15, 22, 27, 3, 15, 10, ...  1
16      [15, 15, 15, 27, 28, 15, 19, 28, 11, 9, 20, 5,...  0
17      [11, 18, 5, 19, 20, 28, 1, 14, 19, 11, 15, 5, ...  0
18      [2, 5, 10, 19, 5, 14, 1, 12, 9, 5, 22, 27, 5, ...  1
19      [18, 25, 19, 13, 1, 20, 15, 22, 1, 27, 6, 12, ...  1
20      [16, 1, 10, 9, 19, 2, 5, 11, 15, 22, 27, 13, 9...  1
21      [4, 15, 14, 27, 5, 22, 7, 5, 14, 9, 1, 27, 19,...  1
22      [19, 1, 13, 1, 20, 15, 22, 1, 27, 5, 18, 11, 9...  1
23      [19, 9, 15, 27, 19, 5, 12, 28, 19, 11, 15, 5, ...  0
24      [20, 15, 22, 19, 20, 9, 11, 27, 22, 9, 11, 20,...  1
25      [9, 19, 13, 1, 9, 12, 15, 22, 27, 1, 4, 9, 12,...  1
26      [11, 21, 18, 13, 21, 19, 21, 5, 22, 27, 19, 1,...  1
27      [15, 15, 15, 27, 28, 1, 14, 20, 1, 18, 5, 19, 28]  0
28      [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
29      [13, 1, 13, 1, 5, 22, 1, 27, 19, 1, 12, 20, 1,...  1
...                                                   ... ..
189582  [15, 15, 15, 27, 28, 1, 11, 28, 19, 21, 21, 27...  0
189583    [27, 10, 9, 1, 14, 27, 28, 4, 26, 9, 1, 14, 28]  0
189584                                [19, 21, 12, 5, 10]  0
189585  [1, 10, 19, 1, 18, 1, 11, 21, 14, 15, 22, 27, ...  1
189586  [15, 19, 15, 15, 27, 28, 2, 5, 11, 5, 13, 27, ...  0
189587  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189588  [16, 16, 27, 28, 28, 1, 26, 1, 13, 1, 20, 28, 28]  0
189589  [10, 1, 19, 8, 28, 1, 18, 20, 27, 28, 26, 1, 1...  0
189590  [21, 3, 18, 5, 26, 4, 5, 14, 9, 5, 27, 28, 13,...  0
189591  [18, 1, 26, 26, 1, 11, 15, 22, 1, 27, 7, 21, 1...  1
189592  [20, 5, 8, 14, 9, 3, 5, 19, 11, 9, 10, 27, 11,...  0
189593              [15, 19, 28, 27, 2, 1, 26, 1, 18, 25]  0
189594  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189595                           [26, 26, 28, 26, 15, 12]  0
189596  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189597           [1, 26, 9, 13, 15, 22, 27, 1, 26, 1, 13]  1
189598  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189599  [15, 19, 15, 15, 27, 28, 1, 19, 25, 12, 28, 11...  0
189600  [3, 21, 20, 2, 1, 5, 22, 1, 27, 1, 12, 20, 25,...  1
189601  [1, 11, 25, 2, 1, 5, 22, 27, 19, 21, 18, 1, 14...  1
189602  [19, 15, 11, 18, 1, 22, 9, 27, 13, 15, 4, 26, ...  1
189603  [20, 15, 22, 1, 18, 9, 19, 5, 19, 20, 22, 15, ...  0
189604  [11, 1, 18, 25, 13, 19, 1, 11, 15, 22, 27, 2, ...  1
189605  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189606  [28, 28, 7, 21, 12, 26, 1, 18, 27, 9, 14, 20, ...  0
189607  [2, 5, 11, 9, 18, 15, 22, 27, 1, 10, 4, 1, 18,...  1
189608  [1, 20, 1, 27, 13, 21, 8, 1, 13, 13, 1, 4, 27,...  1
189609  [15, 2, 19, 5, 19, 20, 22, 15, 27, 19, 27, 15,...  0
189610  [7, 1, 12, 9, 1, 19, 11, 1, 18, 15, 22, 1, 27,...  1
189611  [1, 26, 9, 26, 15, 22, 27, 1, 12, 13, 1, 26, 2...  1

[189612 rows x 2 columns]

In [17]:
# Prepare indeces to split dataset
index_60 = int(df.shape[0]*0.6)
index_90 = int(df.shape[0]*0.9)

In [19]:
# Split dataframe into training(60%), test(30%), validation(10%) 
train_df = df.iloc[0:index_60]
test_df = df.iloc[index_60:index_90]
validation_df = df.iloc[index_90:df.shape[0]]

In [21]:
train_df.to_pickle('../prepared_data/train_df_f.pkl')
test_df.to_pickle('../prepared_data/test_df_f.pkl')
validation_df.to_pickle('../prepared_data/validation_df_f.pkl')